<a href="https://colab.research.google.com/github/sascott9655/ADS-504-Machine-Learning/blob/main/HW_3_ADS_504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

The modcloth_final_data.json file, which is a series of JSON objects from a popular clothing store, modcloth.com. Load these objects into a list, and then use pd.DataFrame to convert that list into a dataframe called modcloth_data

In [ ]:
modcloth_data = pd.read_json('/content/sample_data/modcloth_final_data.json', lines=True) # The file is a single JSON array, not line-delimited
print(type(modcloth_data)) #Data frame
modcloth_data.head()

<class 'pandas.core.frame.DataFrame'>

,item_id,waist,size,quality,cup size,hips,bra size,category,bust,height,user_name,length,fit,user_id,shoe size,shoe width,review_summary,review_text
0,123373,29.0,7,5.0,d,38.0,34.0,new,36,5ft 6in,Emily,just right,small,991571,NaN,NaN,NaN,NaN
1,123373,31.0,13,3.0,b,30.0,36.0,new,NaN,5ft 2in,sydneybraden2001,just right,small,587883,NaN,NaN,NaN,NaN
2,123373,30.0,7,2.0,b,NaN,32.0,new,NaN,5ft 7in,Ugggh,slightly long,small,395665,9.0,NaN,NaN,NaN
3,123373,NaN,21,5.0,dd/e,NaN,NaN,new,NaN,NaN,alexmeyer626,just right,fit,875643,NaN,NaN,NaN,NaN
4,123373,NaN,18,5.0,b,NaN,36.0,new,NaN,5ft 2in,dberrones1,slightly long,small,944840,NaN,NaN,NaN,NaN

In [ ]:
modcloth_data.shape

(82790, 18)

In [ ]:
modcloth_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82790 entries, 0 to 82789
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   item_id         82790 non-null  int64
 1   waist           2882 non-null   float64
 2   size            82790 non-null  int64
 3   quality         82722 non-null  float64
 4   cup size        76535 non-null  object
 5   hips            56064 non-null  float64
 6   bra size        76772 non-null  float64
 7   category        82790 non-null  object
 8   bust            11854 non-null  object
 9   height          81683 non-null  object
 10  user_name       82790 non-null  object
 11  length          82755 non-null  object
 12  fit             82790 non-null  object
 13  user_id         82790 non-null  int64
 14  shoe size       27915 non-null  float64
 15  shoe width      18607 non-null  object
 16  review_summary  76065 non-null  object
 17  review_text     76065 non-null  object
dtypes: float64(5), int64(3), object(10)
memory usage: 11.4+ MB

In [ ]:
modcloth_data.describe()

,item_id,waist,size,quality,hips,bra size,user_id,shoe size
count,82790.000000,2882.000000,82790.000000,82722.000000,56064.000000,76772.000000,82790.000000,27915.000000
mean,469325.229170,31.319223,12.661602,3.949058,40.358501,35.972125,498849.564718,8.145818
std,213999.803314,5.302849,8.271952,0.992783,5.827166,3.224907,286356.969459,1.336109
min,123373.000000,20.000000,0.000000,1.000000,30.000000,28.000000,6.000000,5.000000
25%,314980.000000,28.000000,8.000000,3.000000,36.000000,34.000000,252897.750000,7.000000
50%,454030.000000,30.000000,12.000000,4.000000,39.000000,36.000000,497913.500000,8.000000
75%,658440.000000,34.000000,15.000000,5.000000,43.000000,38.000000,744745.250000,9.000000
max,807722.000000,50.000000,38.000000,5.000000,60.000000,48.000000,999972.000000,38.000000

In [ ]:
modcloth_data.isna().sum()
#item_id -> nominal
#waist -> numeric
#size -> numeric
#quality -> discrete(rating)
#cup size -> discrete
#hips -> numeric
#bra size -> numeric
#category -> nominal(discrete)
#bust -> numeric
#height -> numeric
#user_name -> nominal
#length -> discrete
#fit -> discrete
#user_id -> nominal
#shoe_size -> numeric
#shoe_width -> numeric
#review_summary -> nominal
#review_text -> nominal

item_id               0
waist             79908
size                  0
quality              68
cup size           6255
hips              26726
bra size           6018
category              0
bust              70936
height             1107
user_name             0
length               35
fit                   0
user_id               0
shoe size         54875
shoe width        64183
review_summary     6725
review_text        6725
dtype: int64

Create a variable named ‘labels’ using the ‘quality’ column. These are the labels that we will use for the rest of this assignment.

In [ ]:
labels = modcloth_data['quality']

Next, you will transform these data into numerical vectors you can use for classification. For the variables ‘waist’, ’size’, ’hips’, ‘bra size’, and ‘shoe size’ you can use pd.to_numeric(modcloth_data[variable] to convert them to numerical values. Store these in a data frame.

In [ ]:
modcloth_data['bust'].iloc[0] #String
modcloth_data['height'].iloc[0] #String

'5ft 6in'

In [ ]:
modcloth_data['waist'] = pd.to_numeric(modcloth_data['waist'])
modcloth_data['size'] = pd.to_numeric(modcloth_data['size'])
modcloth_data['hips'] = pd.to_numeric(modcloth_data['hips'])
modcloth_data['bra size'] = pd.to_numeric(modcloth_data['bra size'])
modcloth_data['shoe size'] = pd.to_numeric(modcloth_data['shoe size'])

For the next variable, ‘height’, the strings need some processing to convert them into numeric values. You can use pd.apply to apply a transformation to the column of the data frame. Write a short python function to convert these to a meaningful categorical variable: convert the strings to height (in inches). Also, do this for the variable ‘bust’ - there are some outliers that could be handled by writing and applying another python function. Convert height and bust and store the numeric values to the same data frame as the other numeric features.

In [ ]:
##Thought process to build the function
#5ft 6in (first data example
print(type(modcloth_data['height'].iloc[0]))
##Loop inside all column height
#feet = int(modcloth_data['height'].iloc[0].split('ft')[0]) #split is a function that parses out
#print(feet)
#inches = int(modcloth_data['height'].iloc[0].split('ft')[1].split('in')[0])
#print(inches)

<class 'str'>

In [ ]:
#Links that helped me create function:
#https://www.geeksforgeeks.org/python/python-pandas-dataframe-iat/
#https://www.geeksforgeeks.org/python/python-string-split/
#https://www.geeksforgeeks.org/python/python-string-strip/

def convert_feet_to_inches(height): #height will be the feature needed to convert
  for i in range(len(height)):
    if pd.isna(height.iloc[i]): #checks for NaNs and skips over them if present
            continue

    val = str(height.iloc[i]).strip() #convert values to strings so split and
    #strip functions can work. Strip removes spaces and split, isolates parts of
    #a string to remove, so we can extract the number string only.

    if 'ft' in val and 'in' not in val: #checking for values that have just feet
      feet = int(val.split('ft')[0].strip())
      height.iat[i] = feet * 12 #use iat because "it is used to return only a
      #single value and hence works faster than it - GeeksforGeeks"
    elif 'in' in val and 'ft' not in val: #checking for values that have just inches
      inches = int(val.split('in')[0].strip())
      height.iat[i] = inches
    elif 'ft' in val and 'in' in val: #checking for both ft and inches measures
      feet = int(val.split('ft')[0].strip())
      inches = int(val.split('ft')[1].split('in')[0].strip())
      height.iat[i] = feet * 12 + inches

  return height

In [ ]:
#Convert height to be an integer feature
modcloth_data['height'] = convert_feet_to_inches(modcloth_data['height'])
modcloth_data['height'] = pd.to_numeric(modcloth_data['height'])

In [ ]:
##This line of code helped me figure out the bust function
#modcloth_data['bust'].value_counts() #the bust variable has some outliers

In [ ]:
def convert_bust(bust): #bust will be the feature needed to convert
  for i in range(len(bust)):
    val = str(bust.iloc[i])
    if pd.isna(bust.iloc[i]): #checks for NaNs
      continue
    if val == '37-39': #handle the 1 weird exception
      val = '38'
      val = int(val)
      bust.iat[i] = val
    else:
      bust.iat[i] = int(val)

  return bust

In [ ]:
modcloth_data['bust'] = convert_bust(modcloth_data['bust'])
modcloth_data['bust'] = pd.to_numeric(modcloth_data['bust'])

In [ ]:
modcloth_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82790 entries, 0 to 82789
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   item_id         82790 non-null  int64
 1   waist           2882 non-null   float64
 2   size            82790 non-null  int64
 3   quality         82722 non-null  float64
 4   cup size        76535 non-null  object
 5   hips            56064 non-null  float64
 6   bra size        76772 non-null  float64
 7   category        82790 non-null  object
 8   bust            11854 non-null  float64
 9   height          81683 non-null  float64
 10  user_name       82790 non-null  object
 11  length          82755 non-null  object
 12  fit             82790 non-null  object
 13  user_id         82790 non-null  int64
 14  shoe size       27915 non-null  float64
 15  shoe width      18607 non-null  object
 16  review_summary  76065 non-null  object
 17  review_text     76065 non-null  object
dtypes: float64(7), int64(3), object(8)
memory usage: 11.4+ MB